server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

# This property will help us to access the endpoints of these service without knowing the port & IP of service
# We just need to use api-gateway port i.e 8084 (above) and access the endpoints.
# e.g.- "http://localhost:8084/users/all-user"

  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**, /staff/**

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/rating/**



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

